CREATE TABLE `posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`excerpt` text,
	`content` text NOT NULL,
	`category` enum('釣果記録','タックル','テクニック','フィールド') NOT NULL DEFAULT '釣果記録',
	`coverImage` varchar(512),
	`published` boolean NOT NULL DEFAULT false,
	`authorId` int,
	`fishingDate` timestamp,
	`location` varchar(255),
	`depth` int,
	`maxWeight` float,
	`species` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `posts_slug_unique` UNIQUE(`slug`)
);
